### ISSUE TITLE
Sometimes does "Push Editor" w/out being set

### ISSUE THREAD

**Issue by michaelaye** [olmokramer/atom-autohide-tree-view#36] opened 2015-07-31 18:38 UTC
The workaround for me is go to settings and activate - deactivet the "Push Editor" settings, after that it works. I don't know what triggers it not to work but I just did a manual install of Atom 1.0.3 (as auto-update does still not work on OSX) and maybe that put this plugin into some default state (in which it needs a activate-reactive cycle on the "Push Editor" setting to work correctly?

**Comment by olmokramer** [comment] 2015-08-02 11:05
Hi I'm sorry, but I'm on vacation right now. I'll look at this when I get back.

**Comment by dsifford** [comment] 2015-08-08 21:08
@olmokramer to clarify this issue further:

If you have "push editor" disabled and pin the tree-view, once the tree-view is unpinned, the "push editor" setting becomes enabled and will not disable until you cycle the "push editor" checkbox on the options page. 

Hope that helps!

Thanks for your work on this!

**Comment by olmokramer** [comment] 2015-08-09 01:40
Hmmm.. I can't reproduce this. After pinning and unpinning the tree view, is the `pushEditor` setting actually showing as enabled in the settings view?

**Comment by dsifford** [comment] 2015-08-09 03:00
@olmokramer No, sorry for the miscommunication.

The push editor is not showing enabled, but the sidebar _acts_ as if it were enabled until you go to the settings page and then check and uncheck the select box.

**Comment by dsifford** [comment] 2015-08-12 16:04
@olmokramer - Was my explanation adequate? 

If not, heres a screen recording: http://screencast.com/t/izSfNubl

**Comment by michaelaye** [comment] 2015-08-12 18:02
I had this a couple of versions ago exactly as u describe, but cannot reproduce this anymore (OSX 10.10.4, Atom 1.0.6

**Comment by dsifford** [comment] 2015-08-12 18:04
`Windows 10, Atom 1.0.4` here

**Comment by olmokramer** [comment] 2015-08-13 08:06
Hi @dsifford thanks for the explanation and the screencast. I'm sorry I went quiet all of a sudden, but I'm on vacation right now, and I was very busy with preparations etc. I kinda forgot all about these issues. I still haven't been able to reproduce this, but I'll take another look when I'm back.

**Comment by dsifford** [comment] 2015-08-13 16:10
@olmokramer No worries, my friend. Thanks again for your work!

**Comment by D-side** [comment] 2015-08-19 14:28
Hi! I may have found some clues on why that happens, try switching "Show on" to any option that does not involve `touch` (default is `hover+touch`). I'm using `hover` and I'm doing fine.

If that helps, I've left a more complete report in #32, have a look.

**Comment by olmokramer** [comment] 2015-08-21 23:53
@dsifford Can you please open the devtools (<kbd>ctrl+shift+i</kbd>) and then go to the console tab and repeat the procedure to get the unintended behaviour. Does it log an error to the console? If so, can you post the error message and the stack trace?

**Comment by dsifford** [comment] 2015-08-21 23:59
@olmokramer We can probably call my issue the same as the one @D-side excellently describes in #32. I can confirm that this is resolved if I turn off `hover+touch`

**Comment by olmokramer** [comment] 2015-08-22 00:03
Ok thanks! I really do hope that's what causes all this, because I've already fixed that :) To confirm that it's indeed the origin of this problem, installing [atom-touch-events](https://atom.io/packages/atom-touch-events) should fix the issue. If that works I'll publish the new version right away.

**Comment by dsifford** [comment] 2015-08-22 00:09
The issue is completely resolved with atom-touch-events installed. Thanks again for the awesome work! :smile:

**Comment by olmokramer** [comment] 2015-08-22 00:14
Awesome! Thanks for your patience :) New version will be up in a few minutes!

**Closed as completed** 2015-08-22 17:29 UTC
