### ISSUE TITLE
Focus stuck on tree view

### ISSUE THREAD

**Issue by OmgImAlexis** [olmokramer/atom-autohide-tree-view#37] opened 2015-07-31 19:42 UTC
I noticed you just realised a new version and I haven't had a chance to try it on there yet but I've noticed if I click on a file to open it and then swap to another screen using the OSX swipe feature, focus another process and then switch back the keyboard is stuck in the treeview even if I click in the open file. I'm not sure if this is a bug with Atom or your addon but I've only noticed it since I've had this installed.

**Comment by olmokramer** [comment] 2015-08-02 11:06
Hey, I'm on vacation but I'll take a look when I get back. Sorry for the inconvenience...

**Comment by olmokramer** [comment] 2015-08-08 18:03
I can reproduce this, even without leaving the window. I think the solution is pretty simple, so expect it shortly :) I'll let you know when it's done

**Comment by olmokramer** [comment] 2015-08-08 18:23
Ok, a new version is up. Please let me know if it fixes your issues!

**Comment by markushedvall** [comment] 2015-08-08 18:47
I just tried the new update (0.23.3) and I'm still having this problem. Even though I don't know if the cause of my problem is the the same. If I use the tree-view to open a file that is already open in a tab, the focus will be stuck in the tree-view.

**Comment by olmokramer** [comment] 2015-08-08 18:52
Ah yes, I forgot about the case when a file is already open.  I'll fix that tomorrow. Can you confirm that it works when the file is not open?

**Comment by markushedvall** [comment] 2015-08-08 18:55
Okay sound great, thanks! When the file is not open it works perfectly.

**Comment by olmokramer** [comment] 2015-08-09 01:27
Ok, this should be fixed in v0.24.0. Please let me know if it works ok :)

**Comment by markushedvall** [comment] 2015-08-09 08:27
It works fine now. Thanks a lot :)

**Closed as completed** 2015-08-21 23:54 UTC
