### ISSUE TITLE
Hover detection is EXTREMELY unreliable and erratic

### ISSUE THREAD

**Issue by ProLoser** [olmokramer/atom-autohide-tree-view#40] opened 2015-08-06 22:14 UTC
It's sorta driving me nuts

Screenshot of settings:
![image](https://cloud.githubusercontent.com/assets/67395/9124661/d07f054e-3c4d-11e5-8c64-0934fd78cde9.png)

Note that I have my tree on the right side. I have to keep jiggling the mouse around the edge of the screen

**Comment by olmokramer** [comment] 2015-08-08 17:35
This is a duplicate of #38, as you mentioned. I'll close this one and continue discussion over there.

**Closed as completed by olmokramer** 2015-08-08 17:35 UTC
