### ISSUE TITLE
No matching commands in the command palette

### ISSUE THREAD

**Issue by jesperbjerke** [olmokramer/atom-autohide-tree-view#7] opened 2015-02-12 13:04 UTC
therefor, I cannot activate the plugin and nothing happens

**Comment by olmokramer** [comment] 2015-02-12 15:59
I think this is duplicate of https://github.com/olmokramer/atom-autohide-tree-view/issues/6 . I'll take a look at it tonight

**Comment by olmokramer** [comment] 2015-02-13 11:55
Does the 0.13.0 version fix the problem for you?

**Comment by jesperbjerke** [comment] 2015-02-13 12:04
Yep, thanks!

**Comment by olmokramer** [comment] 2015-02-13 12:16
You're welvome :)

**Closed as completed by olmokramer** 2015-02-13 12:16 UTC
