### ISSUE TITLE
hover events not realiably detected

### ISSUE THREAD

**Issue by michaelaye** [olmokramer/atom-autohide-tree-view#38] opened 2015-08-02 00:53 UTC
I keep having problems to activate unhide via mouse hover. Have increased the minwidth to have more area as I thought it's my bad pointing, but I'm pretty sure now it's not me. Will have to deactivate for now to keep productivity up. I'm not a web-tech hacker so I don't know how this all works, so if you need some  special logfiles/errors from some magical JS console somewhere or whatever it is you web-techs do ;) let me know and I'm happy to help in nailing down this problem.
My system is OSX 10.10.4, Atom 1.0.3

**Comment by ProLoser** [comment] 2015-08-06 22:15
I think #40 might be a duplicate of this

**Comment by ProLoser** [comment] 2015-08-06 22:15
@michaelaye my guess (without verifying whatsoever) is it's some sort of z-index stacking order bug

**Comment by michaelaye** [comment] 2015-08-06 23:18
I agree it's a duplicate. Because it's driving me nuts as well. ;)

**Comment by olmokramer** [comment] 2015-08-08 17:36
I think I've found the source of the problem, and a solution :) I'll just put up a new version ASAP, because it is indeed behaving very badly. Expect it in a few minutes and please let me know if it solves your issues.

**Comment by michaelaye** [comment] 2015-08-08 19:32
Hey, this feels much better! Re-enabled! Thanks a lot

**Closed as completed** 2015-08-08 19:33 UTC

**Comment by olmokramer** [comment] 2015-08-09 00:19
Awesome! Thanks for the reply, and for reporting the issue in the first place :)
